#!/usr/bin/env bash

voice="Princess"
hour=`date +"%r"`
message="I AM DONE RUNNING!"
failure_msg="TASK FAILED?!?!?!?!"


# source other scripts
. "${BASH_SOURCE%/*}/email.sh"


yell(){

  $ok 

  if [[ $? -eq 0 ]];
  then
    $(say -v $voice --progress "$message $ok")
    send_email "DONE" "$ok finished at: $hour"
  else
    $(say -v $voice "$failure_msg")
    send_email "FAILED" "$ok"
  fi
}

ok="${@}" 
yell $ok
