#!/usr/bin/env bash
# source other scripts
. "${BASH_SOURCE%/*}/email.sh"
. "${BASH_SOURCE%/*}/.env"
. "${BASH_SOURCE%/*}/slack.sh"

yell(){

  $ok 

  if [[ $? -eq 0 ]];
  then
    $(say -v $voice --progress "$message $ok")
    send_email "DONE" "$ok finished at: $hour"
    slack_notify "DONE" "$ok finished at: $hour"
  else
    $(say -v $voice "$failure_msg")
    send_email "FAILED" "$ok"
    slack_notify "FAILED" "$ok"
  fi
}

ok="${@}" 
yell $ok
